### ISSUE TITLE
Revisar test ejercicio 6

### ISSUE THREAD

**Issue by alejandroereyesb** [Guille-Rubio/Advanced-JS-Asynchronous-code#7]
En el ejecicio 6 de bikram para que te pase el test, dice que devuelvas un objeto como {img,name}, pero en realidad hay que devolver un objeto parecido a este para que te pase los test: {img:{src:{"https://avatars.githubusercontent.com/u/98309901?v=4"},name:"nombreusuario"

**Comment by Guille-Rubio** [comment]
Fixed as per suggestion
